// The Griffin Initiative

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace GINI_UI_GameplayTags
{
	GINIUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Game_HUD);
	GINIUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Game_Modal);
	GINIUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Menu_Modal);
	GINIUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Menu);
	GINIUSERINTERFACE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_System);
}